# Generated by Django 4.2.4 on 2023-08-08 19:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='place')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='habit starts')),
                ('action', models.TextField(verbose_name='action')),
                ('nice_habit', models.BooleanField(default=False, verbose_name='is nice habit')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('MONDAY', 'Mo'), ('TUESDAY', 'Tu'), ('WEDNESDAY', 'We'), ('THURSDAY', 'Th'), ('FRIDAY', 'Fr'), ('SATURDAY', 'Sa'), ('SUNDAY', 'Su')], default='DAILY', verbose_name='frequency')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='reward (only for default habit)')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='duration')),
                ('published', models.BooleanField(default=False, verbose_name='is published')),
                ('linked_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spa_app.habit', verbose_name='linked habit (only for nice habit)')),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
            },
        ),
    ]
